name: Pre Commit

on:
  push:
    # branches:
    #   - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  pre-commit:
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        # All available versions: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
        python-version: 3.11.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run --all-files
